import { Code, Crown, Globe, Palette, Zap } from "lucide-react";

export const plans = [
  {
    id: 0,
    name: "Basic",
    price: "800",
    originalPrice: "1,200",
    currency: "EGP",
    description: "Perfect single page website for personal or small business",
    icon: Code,
    popular: false,
    features: [
      "Landing Page & Dashboard",
      "Responsive Design",
      "Modern UI Design",
      "Mobile Friendly",
      "Basic Contact Form",
      "1 Revision Round",
    ],
    deliveryTime: "3-5 days",
    bgGradient: "from-blue-500/10 to-purple-500/10",
    borderColor: "border-blue-500/20",
    iconColor: "text-blue-500",
  },
  {
    id: 1,
    name: "Standard",
    price: "1,500",
    originalPrice: "2,000",
    currency: "EGP",
    description: "Multi-page website with custom design",
    icon: Palette,
    popular: true,
    features: [
      "Up to 3 Pages",
      "Custom Design",
      "Responsive Layout",
      "Interactive Elements",
      "Contact Form",
      "Social Media Links",
      "2 Revision Rounds",
      "Basic SEO Setup",
    ],
    deliveryTime: "7-10 days",
    bgGradient: "from-[#ffb400]/10 to-[#ff8c00]/10",
    borderColor: "border-[#ffb400]/40",
    iconColor: "text-[#ffb400]",
  },
  {
    id: 2,
    name: "Premium",
    price: "2,500",
    originalPrice: "3,200",
    currency: "EGP",
    description: "Complete website solution with advanced features",
    icon: Crown,
    popular: false,
    features: [
      "Up to 5 Pages",
      "Premium Custom Design",
      "Smooth Animations",
      "Advanced Interactions",
      "Portfolio/Gallery Section",
      "Blog Layout (if needed)",
      "3 Revision Rounds",
      "SEO Optimization",
      "1 Month Free Updates",
    ],
    deliveryTime: "10-15 days",
    bgGradient: "from-purple-500/10 to-pink-500/10",
    borderColor: "border-purple-500/20",
    iconColor: "text-purple-500",
  },
];

export const extraServices = [
  {
    name: "Extra Page",
    price: "200 EGP",
    icon: Globe,
    description: "Add additional pages to any package",
  },
  {
    name: "Multi-language",
    price: "250 EGP",
    icon: Globe,
    description: "Prepare your website for adding multiple languages",
  },
  {
    name: "Quick Fixes",
    price: "150 EGP",
    icon: Zap,
    description: "Small changes or bug fixes",
  },
];
